EX1:
- ex1/*
- ex1/**/*

EX2:
- ex2/*
- ex2/**/*

EX3:
- ex3/*
- ex3/**/*

EX4:
- ex4/*
- ex4/**/*

EX5:
- ex5/*
- ex5/**/*

EX6:
- ex6/*
- ex6/**/*

EX7:
- ex7/*
- ex7/**/*

EX8:
- ex8/*
- ex8/**/*

EX9:
- ex9/*
- ex9/**/*
